# name: CI/CD Pipeline for Vite React App

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install Dependencies
#         run: npm install

#       # - name: Run Tests
#       #   run: npm test --if-present

#       - name: Build Project
#         run: npm run build

name: LIGHTHOUSE ACCES CI
on:
  push:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Désactiver Nexus et forcer npm public
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "strict-ssl=false" >> ~/.npmrc
          npm config list

      - name: Supprimer éventuelles dépendances Nexus
        run: rm -rf node_modules package-lock.json

      - name: Installer les dépendances depuis npm public
        run: npm install --no-cache --prefer-online

      - name: Installer Lighthouse CI
        run: npm install -g @lhci/cli@0.14.x

      - name: Build project
        run: npm run build

      - name: Run Lighthouse CI
        run: lhci autorun
